/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Convert a RGBA buffer to ATEM YUV422 packing in the correct colorspace
 *
 * This is performed synchronously
 *
 * @param width - The width of the image
 * @param height - The height of the image
 * @param data - The input pixel data
 */
export function convertRgbaToYuv422(width: number, height: number, input: Buffer, output: Buffer): void
